const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:8000";

export async function analyzeDomain(domain, threshold) {
    const res = await fetch(`${API_BASE}/analyze-domain`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ domain, threshold: threshold || null }),
    });
    if (!res.ok) {
        const err = await res.json().catch(() => ({ detail: "Unknown error" }));
        throw new Error(err.detail || "Failed to analyze domain");
    }
    return res.json();
}

export async function analyzeRegion(region, threshold) {
    const res = await fetch(`${API_BASE}/analyze-region`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ region, threshold }),
    });
    if (!res.ok) {
        const err = await res.json().catch(() => ({ detail: "Unknown error" }));
        throw new Error(err.detail || "Failed to analyze region");
    }
    return res.json();
}

export async function generateReports(analysisData) {
    const res = await fetch(`${API_BASE}/generate-report`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(analysisData),
    });
    if (!res.ok) {
        const err = await res.json().catch(() => ({ detail: "Unknown error" }));
        throw new Error(err.detail || "Failed to generate reports");
    }
    return res.json();
}

export function getReportUrl(path) {
    if (!path) return null;
    return `${API_BASE}${path}`;
}

// ─── Mock for offline development ─────────────────────────────────────────
export const MOCK_DOMAIN_RESPONSE = {
    mode: "DOMAIN",
    domain: "druva.com",
    threshold: "10Cr+",
    company_dossier: {
        industry: "Cloud Data Protection & Cyber Resilience",
        business_stage: "Mature / Late Growth",
        hiring_intensity: "Medium",
        signal_count: 45,
        growth_signals: [
            "Gartner MQ Leader 2025",
            "Estimated $300M ARR",
            "Microsoft Azure partnership expansion",
        ],
        scale_signals: [
            "$475M raised",
            "$2B valuation",
            "FedRAMP authorized",
            "Global offices (Pune, Sunnyvale, UK)",
        ],
        trigger_events: [
            "New CFO appointed Feb 2025",
            "Azure partnership launch Mar 2025",
            "33% AI-code mandate by end-2025",
        ],
        strategic_pressure_score: 85,
    },
    strategic_bottlenecks: [
        {
            title: "AI Integration Gap",
            severity: "High",
            evidence:
                "CEO targets 33% of code written by AI by end-2025, creating massive testing and quality integration complexity.",
            mapped_service: "Legacy Modernization AI",
            icon: "Cpu",
        },
        {
            title: "Microfrontend Modernization",
            severity: "Medium",
            evidence:
                "Currently transitioning UI to a multi-level microfrontend architecture while scaling AWS/Azure operations.",
            mapped_service: "Legacy Modernization AI",
            icon: "Layers",
        },
        {
            title: "GTM Efficiency Drain",
            severity: "High",
            evidence:
                "Azure partnership requires scaling outreach without adding SDR headcount due to 'muted' hiring stance.",
            mapped_service: "Market Intelligence Agent",
            icon: "Zap",
        },
    ],
    lead_score: {
        scores: {
            "Industry Fit": 95,
            Budget: 90,
            Growth: 85,
            Bottlenecks: 90,
            Alignment: 95,
        },
        total: 92,
        classification: "Strong Lead",
        has_trigger_event: true,
        strategic_pressure: 85,
    },
    why_now:
        "Classification: Strong Lead. Trigger events detected: New CFO (Feb 2025); Azure partnership (Mar 2025); 33% AI-code mandate — Converging signals create a strategic window for engagement.",
    personalized_outreach: {
        recommended_decision_maker: "Stephen Manley, CTO",
        strategic_angle:
            "Accelerating the public 33% AI-code mandate through automated integration and testing of AI-authored code.",
        outreach_email:
            "Stephen,\n\nCongratulations on the Gartner MQ Leader recognition — being the first pure-SaaS vendor in that quadrant is a meaningful inflection point.\n\nI've been following Jaspreet's public comments on the AI-code mandate, specifically the target of having a third of Druva's code AI-generated by end of 2025. That's an ambitious technical transformation, especially while simultaneously migrating to a microfrontend architecture.\n\nWe work with engineering organizations navigating exactly this transition. Our Legacy Modernization AI automates the workflow integration layer between AI-generated code and existing production codebases — addressing the testing, quality, and deployment pipeline challenges that surface when AI-authored code reaches 20%+ of the codebase.\n\nWould a 15-minute conversation on how we've helped similar-scale SaaS engineering teams accelerate this transition be useful?\n\nBest,\n[Name]\nDataVex",
    },
    agent_research_trace: [
        {
            step: 1,
            type: "Data Acquisition",
            detail: "Retrieved latest funding rounds and valuation data ($475M raised, Series H).",
            timestamp: "2026-02-21 20:45:12",
        },
        {
            step: 2,
            type: "Signal Extraction",
            detail: "Identified AI-first hiring strategy and microfrontend migration roadmap.",
            timestamp: "2026-02-21 20:46:05",
        },
        {
            step: 3,
            type: "Strategic Inference",
            detail: "Mapped public CEO mandate to DataVex Modernization framework.",
            timestamp: "2026-02-21 20:46:45",
        },
        {
            step: 4,
            type: "Bottleneck Detection",
            detail: "Detected 3 high-severity strategic bottlenecks aligned with DataVex catalog.",
            timestamp: "2026-02-21 20:47:02",
        },
        {
            step: 5,
            type: "Scoring Engine",
            detail: "Calculated 92/100 weighted score based on budget signals and trigger timing.",
            timestamp: "2026-02-21 20:47:10",
        },
    ],
};

export const MOCK_REGION_RESPONSE = [
    {
        company_name: "Druva Inc.",
        website: "druva.com",
        industry: "Cloud Data Protection",
        business_stage: "Late Growth",
        revenue_likelihood: "Likely meets 10Cr+",
        supporting_signals: ["$475M raised", "Gartner Leader", "Global offices"],
        confidence_level: "High",
    },
    {
        company_name: "Freshworks",
        website: "freshworks.com",
        industry: "SaaS CRM",
        business_stage: "Public Company",
        revenue_likelihood: "Likely meets 10Cr+",
        supporting_signals: ["NASDAQ listed", "Global customer base", "AI product suite"],
        confidence_level: "High",
    },
    {
        company_name: "Postman",
        website: "postman.com",
        industry: "DevTools / API Platform",
        business_stage: "Mid Growth",
        revenue_likelihood: "Possibly meets 10Cr+",
        supporting_signals: ["25M+ users", "Enterprise pricing", "Active hiring"],
        confidence_level: "Medium",
    },
];
